---
- name: New MOTD using variable
  hosts: all
  become: yes
  
  vars:
    motd_message: |
      Добро пожаловать в систему!
      Дата: {{ ansible_date_time.date }}
      Время: {{ ansible_date_time.time }}
      
  tasks:
    - name: Create a temporary file with a message
      copy:
        content: "{{ motd_message }}"
        dest: /tmp/new_motd.txt
        
    - name: Installing a new MOTD
      command: cp /tmp/new_motd.txt /etc/motd
      
    - name: Deleting a temporary file
      file:
        path: /tmp/new_motd.txt
        state: absent